write POST API to add more key and value
vutran1710/magellan pull request #2
Opened 2019-10-09 19:22 UTC by yamadaken93

2019-10-10 02:20 UTC, vutran1710 requested changes
Chưa có code phần 1 mà đã PR phần này là sao em. Phần 1 của bạn kia a chưa approve nhé

2019-10-10 07:45 UTC, vutran1710 commented on app.py
> +        return RESULT
Chạy thử, gửi request test thử chưa mà submit lên đây?

2019-10-10 07:45 UTC, vutran1710 commented on app.py
> +    else:
Nếu trong if có return, thì sau return ko cần else nữa

2019-10-10 07:46 UTC, vutran1710 commented on app.py
> +    if request.method == 'POST' and request.is_json:
`methods=['POST']` thì ko cần check request.method nữa chứ nhỉ? Gọi = 1 method khác nó sẽ văng lỗi response về liền

2019-10-10 07:46 UTC, vutran1710 requested changes
Kiểm tra

2019-10-11 05:02 UTC, alexnguyen2201 reviewed
Yêu cầu của task là add more one, cho nên phải kiểm tra trước xem số lượng key trong request_json_body có >1 không nữa,

2019-10-11 06:12 UTC, yamadaken93 commented
mình mới sửa lại 2 bạn review giúp mình.

2019-10-11 19:24 UTC, closed without merging